name: Azure Pipelines
variables:
  python.version: '3.7.6'
  sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC1+RFxpYPGklsmGScM31+e6SLuV+0A0yGVKaTh5lEemZyuC7nHqQojMOMn8YFGT2YQjBN9U2hYu6vct9wy//B/xruJ7+/2XAOIJQOXRWidsj7BeoX775D5zemHfNyAdHc/+ePrVLXZmn1GiyZJxO9EwgZpKGW9efthBF7bAS9nAFDLD/BNP7m8D+cVjW8HewXl/wju/ew17wBZFIt0PDDwwbjBisXOzUkKSw0n8VyYmo4CyW9gRQmXPPKKFX+XTmT5rGW2Z2/nBqp6tktp2rUYiG33i+Ylkpe5WDpyLObzp3vsfRQVDVeEAyZfAwiYQ6Cm1QY3/+048W8eiwLOa40mW3qYkcCjUVLZ6bR/rHCmrpyyo2ILc4sHaFxqFhP3I0QSmtve9w3htrgI3+CwdG/5f2TstRn3CqBeuKFf06lT/zYHi+Rf98arn48skR2hgTKKMfFaxP353moHyshzo37caGP297ZobobU4bhZrV/4hUEgbHX5OtoX7TvyfMmcsiU='
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-20.04'
      name: myAgentPool
    steps:
    # Needed for Terraform VM deployment
    - task: InstallSSHKey@0
      inputs:
        knownHostsEntry: 'AAAAB3NzaC1yc2EAAAADAQABAAABgQC1+RFxpYPGklsmGScM31+e6SLuV+0A0yGVKaTh5lEemZyuC7nHqQojMOMn8YFGT2YQjBN9U2hYu6vct9wy//B/xruJ7+/2XAOIJQOXRWidsj7BeoX775D5zemHfNyAdHc/+ePrVLXZmn1GiyZJxO9EwgZpKGW9efthBF7bAS9nAFDLD/BNP7m8D+cVjW8HewXl/wju/ew17wBZFIt0PDDwwbjBisXOzUkKSw0n8VyYmo4CyW9gRQmXPPKKFX+XTmT5rGW2Z2/nBqp6tktp2rUYiG33i+Ylkpe5WDpyLObzp3vsfRQVDVeEAyZfAwiYQ6Cm1QY3/+048W8eiwLOa40mW3qYkcCjUVLZ6bR/rHCmrpyyo2ILc4sHaFxqFhP3I0QSmtve9w3htrgI3+CwdG/5f2TstRn3CqBeuKFf06lT/zYHi+Rf98arn48skR2hgTKKMfFaxP353moHyshzo37caGP297ZobobU4bhZrV/4hUEgbHX5OtoX7TvyfMmcsiU='
        sshPublicKey: $(sshPublicKey)
        #sshKeySecureFile: 'id_rsa'
    
    - task: TerraformCLI@0
      inputs:
        command: 'validate'
        allowTelemetryCollection: true

    - task: TerraformInstaller@0
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'

    - task: TerraformCLI@0
      displayName: 'terraform init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: 'terraform'
        backendServiceArm: '09e822a9-d2e3-40f8-885b-ae82ab7bffdd'
        backendAzureRmResourceGroupName: 'Azuredevops'
        backendAzureRmStorageAccountName: 'storage93udacitydevops'
        backendAzureRmContainerName: 'mycontainer'
        backendAzureRmKey: 'tf/terraform.tfstate'

    - task: TerraformCLI@0
      displayName: 'terraform apply'
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: 'terraform'
        environmentServiceNameAzureRm: '09e822a9-d2e3-40f8-885b-ae82ab7bffdd'


    - task: ArchiveFiles@2
      displayName: 'Archive FakeRestAPI'
      inputs:
        rootFolderOrFile: 'path/to/fakerestapi'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip'
    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip
      displayName: 'Upload Package'
      artifact: drop-fakerestapi
- stage:
  jobs:
  - deployment: FakeRestAPI
    pool:
      vmImage: 'Ubuntu-16.04'
    environment: 'TEST'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App'
            inputs:
              azureSubscription: ''
              appName: ''
              appType: webApp
              package: $(Pipeline.Workspace)/drop-fakerestapi/$(Build.BuildId)-fakerestapi.zip
  # - deployment: VMDeploy
  #   displayName: NAME
  #   environment:
  #     name:  ENVIRONMENT NAME
  #     resourceType: VirtualMachine
  #     tags: TAG NAME
  #   strategy:
  #     runOnce:
  #       deploy:
  #         steps:
  #         - task: Bash@3
  #           inputs:
  #             targetType: 'inline'
  #             script: |
  #               #! /bin/bash
                
  #               sudo apt-get upgrade -y
  #               sudo apt-get install python3-pip -y
  #               sudo apt-get install unzip -y
  #               sudo apt-get install -y chromium-browser
  #               pip3 install selenium
  #               export PATH=$PATH:some/path


